### ISSUE TITLE
dio ^5.0.0 and network_logger any, version solving failed

### ISSUE THREAD

**Issue by karthikeyanmarutham** [themisir/flutter-network-logger#16]
Running "flutter pub get" in Flutter...
Resolving dependencies...
Because network_logger >=1.0.0 depends on dio ^4.0.0 and network_logger <1.0.0 depends on dio ^3.0.10, every version of network_logger requires dio ^3.0.10 or ^4.0.0.
So, because mindari depends on both dio ^5.0.0 and network_logger any, version solving failed.
pub get failed
command: "/Users/karthick/developement/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
pub env: {
  "FLUTTER_ROOT": "/Users/karthick/developement/flutter",
  "PUB_ENVIRONMENT": "vscode.dart-code:flutter_cli:get",
  "PUB_CACHE": "/Users/karthick/.pub-cache",
}

**Comment by themisir** [comment]
Fixed. Please run `pub get` to download the latest version.
