### ISSUE TITLE
TabAlignment issue on check request detail

### ISSUE THREAD

**Issue by gwijaya94** [themisir/flutter-network-logger#18]
Hi, is there any solution or fixing regarding this issue? 
Thankyou.

<img width="679" alt="image" src="https://github.com/themisir/flutter-network-logger/assets/65438712/b70b1d0d-123f-47ce-a135-43b0c287ea52">

Device:
<img width="224" alt="image" src="https://github.com/themisir/flutter-network-logger/assets/65438712/24768a2b-a56a-4995-8f81-e0dcfd02fd51">

```
> flutter doctor -v
[√] Flutter (Channel stable, 3.16.2, on Microsoft Windows [Version 10.0.22621.2715], locale en-ID)
    • Flutter version 3.16.2 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (3 months ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

```

**Comment by themisir** [comment]
This one seems like an app specific issue rather than caused by this package. Last time I checked it was working fine. That said I don't really have the bandwidth to look into this issue right now.

**Comment by gwijaya94** [comment]
Hi @themisir, thankyou for the fast response.
Just found out the issue. The cause is from my app theme under tabBarTheme, I set globally its tabAlignment value there.
After remove it, no error shown anymore.

Gonna close this issue, thankyou.
