### ISSUE TITLE
Dio interceptor: blocks every event

### ISSUE THREAD

**Issue by ArinFaraj** [themisir/flutter-network-logger#5]
From the `dio` documentations
> If you want to continue the request, call [handler.next].

However, in this package, the interceptor never uses the handler and therefore does not send events to the next interceptor, causing the event to be blocked.

Fix:
Just add `handler.next` at the end of each event ie. onRequest, onResponse ...

**Comment by themisir** [comment]
Yes and no. Check [this](https://github.com/themisir/flutter-network-logger/blob/master/lib/src/channels/dio.dart#L16) and [this](https://github.com/themisir/flutter-network-logger/blob/master/lib/src/channels/dio.dart#L30) lines. `super.onRequest` and `super.onResponse` are already calling handler.next.

**Comment by ArinFaraj** [comment]
That's true my bad, its really strange this interceptor still blocks every event for me even tho its perfectly normal, thanks for the reply 💙

**Comment by themisir** [comment]
Hm that's strange, maybe dio interceptor behavior changed again.. Can you debug and set a breakpoint on `super.onRequest` or `super.onResponse` to see what happens and where it stucks?

**Comment by ArinFaraj** [comment]
Found the issue 
the version 1.0.0 on pub.dev doesn't have the super calls, probably you forgot to update it there.
and probably thats why i made the issue cause i didn't see it there 

![image](https://user-images.githubusercontent.com/13029655/162605040-04e896af-2293-4d03-a58b-dcb6abccfa76.png)

**Comment by themisir** [comment]
Outch, let me update, sorry for that!
