### ISSUE TITLE
is this package support chopper?

### ISSUE THREAD

**Issue by hatemragab** [themisir/flutter-network-logger#6]
can i add this interceptor to chopper?

**Comment by themisir** [comment]
It doesn't have built-in chopper integration. However it's pretty simple to write your own interceptor to collect logs.

Check out those resources if you're interested:

- https://github.com/themisir/flutter-network-logger/blob/master/lib/src/channels/dio.dart (Dio interceptor source code)
- https://github.com/lejard-h/chopper/blob/develop/interceptors.md (Chopper interceptor docs)
- https://github.com/lejard-h/chopper/blob/develop/chopper/lib/src/interceptor.dart#L171-L211 (Chopper interceptor sample)

As you can see Chopper and Dio interceptors are pretty similar. The only challenge is to match responses with corresponding requests, which I don't have any idea how that could be done 😅

**Comment by hatemragab** [comment]
For unknown reason the build in chopper http log interceptor not logging with me
