### ISSUE TITLE
Draggable NetworkLoggerButton?

### ISSUE THREAD

**Issue by itsJoKr** [themisir/flutter-network-logger#8]
@themisir We use NetworkLoggerButton and sometimes it would obstruct the view/button behind it.

We have a version where onLongPress, the button would enter in drag mode and you can drag it to a better position. Would you approve this kind of change? We would clean it up and make PR?

**Comment by themisir** [comment]
Sure if you have a suggestion we can apply it. Just make sure to not use any third party package for such interaction (I want to keep package tree as small as possible).
